ThreadPool Refactor.
AlwaysColorado/455Homework2 pull request #15
Opened 2022-03-04 23:15 UTC by MaximillianWhelan

2022-03-04 23:25 UTC, sixfobit commented on src/main/java/cs455/scaling/threadpool/ThreadPool.java
> +        }
The synchronized block above should be in an unending, but terminatable (Atomic Boolean?) loop in this class's equivalent of run() (In fact, should this be a thread?)  The worker arary should also probably be initialized and waiting before this starts.

2022-03-04 23:25 UTC, sixfobit commented on src/main/java/cs455/scaling/threadpool/ThreadPool.java
> +    public ThreadPool(int threadPoolSize) throws InterruptedException {
If we wanna synchronize on the batchList, it'd probably be a good idea for this constructor to take a reference to the list, passed in from TPM.

2022-03-04 23:26 UTC, sixfobit commented on src/main/java/cs455/scaling/threadpool/ThreadPool.java
> +        private AtomicBoolean running = new AtomicBoolean(true);
It's a bit pedantic, but I think the best practice here would be to initialize to false, then set running to true as the first line in run().

2022-03-04 23:28 UTC, sixfobit commented on src/main/java/cs455/scaling/threadpool/ThreadPool.java
> +            running = new AtomicBoolean(false);
Again, a bit pedantic, but the boolean method has a .set(new value) method you can use instead of creating a new object to assign. (this also goes for 68 and 74.

2022-03-04 23:31 UTC, sixfobit commented on src/main/java/cs455/scaling/threadpool/ThreadPool.java
>                          }
For this to work, something has to currently own a lock on the specific taskList variable you wanna work with, and notify(). Is it possible to refactor the task to start when TP calls a helper method in Worker giving it a taskList?

2022-03-04 23:33 UTC, sixfobit commented on src/main/java/cs455/scaling/threadpool/ThreadPool.java
> +                    task = taskList.poll();
We're gonna need to poll() the listuntil it's tempty(aka there's no tasks left to work on).
I think the flow here would be available.set(false), while(notempty): poll a task, .executeTask, then set available(true) when everything is done.

2022-03-04 23:37 UTC, sixfobit commented on src/main/java/cs455/scaling/threadpool/ThreadPool.java
> +        }
As far as the constructor goes, I think all it needs to do is start each thread, we can probably worry about availability later.

2022-03-04 23:38 UTC, sixfobit commented on src/main/java/cs455/scaling/threadpool/ThreadPool.java
> +    public ThreadPool(int threadPoolSize) throws InterruptedException {
Actually nevermind this works fine, misread.

2022-03-08 13:23 UTC, MaximillianWhelan commented on src/main/java/cs455/scaling/threadpool/ThreadPool.java
> +        }
I am not sure it needs a loop, because it will only poll if there are things there, and that is handled via TPM so I think the current implementation is fine

2022-03-08 13:24 UTC, MaximillianWhelan commented on src/main/java/cs455/scaling/threadpool/ThreadPool.java
> +        private AtomicBoolean running = new AtomicBoolean(true);
fixed

2022-03-08 17:22 UTC, sixfobit requested changes

2022-03-08 17:22 UTC, sixfobit commented on src/main/java/cs455/scaling/threadpool/ThreadPool.java
> +        }
My concern is that this'll only poll() once ever, while TPM will be constantly creating new taskLists and adding them to the batchList. That's why I think this needs to be handled async, because it's gotta constantly be trying to empty the queue, just like the worker thread is constantly trying to empty its taskList.

2022-03-11 18:18 UTC, sixfobit requested changes

2022-03-11 18:18 UTC, sixfobit commented on src/main/java/cs455/scaling/threadpool/ThreadPool.java
> +            this.taskList.notify();
This should probably be in a synchronized block, to avoid lock acquisition errors.

2022-03-11 18:18 UTC, sixfobit commented on src/main/java/cs455/scaling/threadpool/ThreadPool.java
>              }
This scope is too large for the synchronized block- keep it as small as possible: end it after .wait(), or execution may pause. (I ran into this issue in HW1)

2022-03-11 18:18 UTC, sixfobit commented on src/main/java/cs455/scaling/threadpool/ThreadPool.java
>              }
This scope is too large for the synchronized block- keep it as small as possible: end it after .poll(), or execution may pause.

2022-03-11 18:18 UTC, sixfobit commented on src/main/java/cs455/scaling/threadpool/ThreadPool.java
>                          assert task != null;
LinkedBlockingQueue doesn't allow null elements, I don't think we need this try/catch.

The only time we'd get null from a poll() is if the taskList is empty.

2022-03-11 18:18 UTC, sixfobit commented on src/main/java/cs455/scaling/threadpool/ThreadPool.java
>                          assert task != null;
LinkedBlockingQueue doesn't allow null elements, I don't think we need this try/catch.

The only time we'd get null from a poll() is if the taskList is empty.

2022-03-11 18:18 UTC, sixfobit commented on src/main/java/cs455/scaling/threadpool/ThreadPool.java
> +           counter++;
counter is never reset to 0, so we'll eventually get a nullpointerexception.

2022-03-11 18:18 UTC, sixfobit commented on src/main/java/cs455/scaling/threadpool/ThreadPool.java
> +           counter++;
counter is never reset to 0, so we'll eventually get an ArrayOutOfBounds exception.

2022-03-14 22:54 UTC, merged