TPMgr
AlwaysColorado/455Homework2 pull request #16
Opened 2022-03-05 00:10 UTC by AlwaysColorado

Need to main with this branch to hangle addTaskList() error

2022-03-05 00:22 UTC, sixfobit commented on src/main/java/cs455/scaling/threadpool/ThreadPoolManager.java
> +            taskList = new LinkedBlockingQueue<>();
Make sure to initialize with batchSize for capacity

2022-03-05 00:32 UTC, sixfobit requested changes

2022-03-05 00:32 UTC, sixfobit commented on src/main/java/cs455/scaling/threadpool/ThreadPoolManager.java
> +        }
Currently, this will only allow for a tasklist to get added to the batch once both: A: the amount of specified time has passed & B: a new task gets added. Do we want to push the batchList on right at expiry?

2022-03-05 00:32 UTC, sixfobit commented on src/main/java/cs455/scaling/threadpool/ThreadPoolManager.java
> +    }
Currently, this thread will start and die right away- need some sort of loop to keep it alive. Worker's got a great example of how to make a threadsafe While(true) loop that you could use in run() here.

2022-03-05 00:32 UTC, sixfobit commented on src/main/java/cs455/scaling/threadpool/ThreadPoolManager.java
> +        return ( timePast > batchTime ? true : false );
might want >= to capture the (unlikely) event of timePast = batchTime.

2022-03-05 00:32 UTC, sixfobit commented on src/main/java/cs455/scaling/threadpool/ThreadPoolManager.java
> +        taskList.offer(task);
With line 39 above, this might result in a double-offer to taskList.

2022-03-06 16:59 UTC, MaximillianWhelan commented on src/main/java/cs455/scaling/threadpool/ThreadPoolManager.java
> +        return ( timePast > batchTime ? true : false );
This could also be achieved by using a timer task, and then you can just set the time to batchtime, rather than having this logic. Just an idea. Plus with timer it can do something based on the timer, i.e. implement a run method which sends the relevant data to the threadpool, or whatever needs to be achieved.

2022-03-09 19:00 UTC, AlwaysColorado commented
I apologize - I had created a PR make it easy to find, but should have just pushed the branch to remote.  I knew it wasn't ready, but was working through details in my brain.  

I believe it should be okay now. Take a peek and let me know.  

I DID add a terminate() method that server could call to close the run() while loop.  It allows the remaining taskList to be pushed to the ThreadPool.

2022-03-09 19:05 UTC, AlwaysColorado commented on src/main/java/cs455/scaling/threadpool/ThreadPoolManager.java
> +        return ( timePast > batchTime ? true : false );
I'll look at the timer task again. I looked at it a bit, but wasn't sure it would work here since I am not spawning a new thread each time a taskList is created.  Since the tasks are coming from a single thread, the requests should be serialized ultimately.

2022-03-14 20:15 UTC, sixfobit approved these changes
Looks good!

2022-03-14 22:49 UTC, merged